# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    paths:
      - '**/*.py'
    branches: [ "main" ]
  pull_request:
    paths:
      - '**/*.py'
    types: [review_requested, ready_for_review]
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  static_analysis:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
          ruff check .
        working-directory: ./backend
  #    - name: Format with ruff
  #      run: |
  #        ruff format --check --diff .
  #      working-directory: ./backend

  unit_tests:

     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v4
       - name: Set up Python 3.12
         uses: actions/setup-python@v3
         with:
           python-version: "3.12"
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install pytest
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
       - name: Test with pytest
         run: |
           pytest
         working-directory: ./backend
